### ISSUE TITLE
Cannot compile JSDoc

### ISSUE THREAD

**Issue by andreydos** [bvanderlaan/jsdoc-route-plugin#1]
I have Express project and for compiling docs I use "gulp-jsdoc3". I have install plugin and get error in console "Error: Cannot find module '/tmp/jsdoc-route-plugin'"
I try to copy folder manually to './tmp/jsdoc-route-plugin' or './node_modules/tmp/jsdoc-route-plugin'  but the same error still in the console.

**Comment by tmathews** [comment]
Change your jsdoc configuration JSON to reference the directory like so:

```
"plugins": ["./node_modules/jsdoc-route-plugin"],
```

**Comment by tmathews** [comment]
@bvanderlaan Please update documentation to be more clear and correct (--config is not an option for jsdoc). Thanks.

**Comment by andreydos** [comment]
@tmathews Thanks for help!
